version: "3.7"

services:
    react:
        container_name: ClashRoyale-frontend
        image: frontend:dev
        ports:
        - 8000:3000
        environment:
        - CHOKIDAR_USEPOLLING=true
        depends_on:
        - express

    express: 
        container_name: ClashRoyale-backend
        image: backend:dev
        ports:
        - 3001:3001
        environment:
        - CHOKIDAR_USEPOLLING=true
